// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using e_liqueur.Models;

namespace e_liqueur.Migrations
{
    [DbContext(typeof(LiquorContext))]
    [Migration("20200821094433_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.7");

            modelBuilder.Entity("e_liqueur.Models.StockItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Stock");
                });

            modelBuilder.Entity("e_liqueur.Models.Store", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Stores");
                });

            modelBuilder.Entity("e_liqueur.Models.StoreStockItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Quantity")
                        .HasColumnType("REAL");

                    b.Property<long?>("StockItemId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("StoreId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("StockItemId");

                    b.HasIndex("StoreId");

                    b.ToTable("StoreStockItem");
                });

            modelBuilder.Entity("e_liqueur.Models.StoreStockItem", b =>
                {
                    b.HasOne("e_liqueur.Models.StockItem", "StockItem")
                        .WithMany()
                        .HasForeignKey("StockItemId");

                    b.HasOne("e_liqueur.Models.Store", null)
                        .WithMany("Stock")
                        .HasForeignKey("StoreId");
                });
#pragma warning restore 612, 618
        }
    }
}
